server:
    port: 8081 
    
spring:
    application:
        name: book-service

    datasource:
        username: admin
        password: admin
        url: jdbc:mysql://localhost:3306/sb_ms
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

        properties:
            '[hibernate.format_sql]': true

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka

application:
    service-url:
        author-service: http://localhost:8082/api/v1/author
