server.port=8080

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=BOOK-SERVICE
spring.cloud.gateway.routes[0].uri=lb://BOOK-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/books/**

spring.cloud.gateway.routes[1].id=AUTHOR-SERVICE
spring.cloud.gateway.routes[1].uri=lb://AUTHOR-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/author/**

spring.cloud.gateway.routes[2].id=CUSTOMER-SERVICE
spring.cloud.gateway.routes[2].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[3].id=CUSTOMER-SERVICE-ROLES
spring.cloud.gateway.routes[3].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/roles/**

spring.cloud.gateway.routes[4].id=DISCOVERY-SERVICE
spring.cloud.gateway.routes[4].uri=http://localhost:8761
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/main
spring.cloud.gateway.routes[4].filters[0]=SetPath=/

spring.cloud.gateway.routes[5].id=DISCOVERY-SERVICE-STATIC
spring.cloud.gateway.routes[5].uri=http://localhost:8761
spring.cloud.gateway.routes[5].predicates[0]=Path=/eureka/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/springboot-microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=springboot-application
jwt.auth.converter.principle-attribute=preferred_username

keycloak.realm=springboot-microservices-realm
keycloak.admin.client-id=admin-cli
keycloak.serviceUrl=http://localhost:8090/
keycloak.client-secret=Ft1If9mD95QsSmJQLIUO25B1v9Lr4EN4

keycloak.client.client-id=springboot-application
keycloak.tokenEndpoint=http://localhost:8090/realms/springboot-microservices-realm/protocol/openid-connect
