server:
  port: 8081 
    
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/sb_ms
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      '[hibernate.format_sql]': true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/springboot-microservices-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: springboot-application
      principle-attribute: preferred_username

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

